public enum PlayerOneStates
{
    PlayerOneIdle,
    PlayerWalkLeft,
    PlayerWalkRight,
    PlayerJump,
    PlayerJumpForward,
    PlayerJumpBackwards,
    ComeDown,
    ComeDownForwards,
    ComeDownBackwards,
    PlayerHighPunch,
    PlayerLowPunch,
    PlayerHighKick,
    PlayerLowKick,
    PlayerHitByLowKick,
    PlayerHitByHighKick,
    PlayerHitByLeftPunch,
    PlayerHitByRightPunch,
    WaitForAnimations,
    PlayerDefeated,
    WaitForHitAnimations,
    PlayerDemo
}
